name: PHP Codeception Tests - master

on:
  workflow_dispatch:
  #push:

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: custom_pages
      install-composer: true
